feat: Make Github/Gitea urls configurable
ludofleury/satisfy pull request #163
Opened 2021-11-11 13:19 UTC by gerdemann

2021-11-11 13:37 UTC, ramunasd requested changes

2021-11-11 13:37 UTC, ramunasd commented on src/Playbloom/Satisfy/Webhook/GithubWebhook.php
> +    /** @var array */
Please define array shape

2021-11-11 13:37 UTC, ramunasd commented on src/Playbloom/Satisfy/Webhook/GithubWebhook.php
> +        ?array $sourceUrls = ['git_url', 'ssh_url', 'clone_url', 'svn_url']
Can You set this default value directly to property?

2021-11-11 13:37 UTC, ramunasd commented on src/Playbloom/Satisfy/Webhook/GithubWebhook.php
> +        $this->sourceUrls = $sourceUrls;
Please use setter for this property as it is optional and set by default.

2021-11-11 13:42 UTC, gerdemann commented
@ramunasd Can you look at it again, please? Is that what you meant?

2021-11-11 13:59 UTC, ramunasd commented
The main point was to move out $sourceUrls from __constructor(), because this parameter is optional. Please set default value directly to class property. Setter mut be called from DI, not constructor.

2021-11-11 14:15 UTC, gerdemann commented
> The main point was to move out $sourceUrls from __constructor(), because this parameter is optional. Please set default value directly to class property. Setter mut be called from DI, not constructor.

I have orientated myself on the secret property. Unfortunately, I'm not that deep in the project. Can you describe what you mean in more detail?

2021-11-12 08:53 UTC, ramunasd commented
I think I was quite clear :)
Nevermind, I will fix this later.

2021-11-12 08:57 UTC, gerdemann commented
Thank you very much.
I had also orientated myself on the Gitlab webhook, where it was done in the same way.

2021-11-17 19:05 UTC, ramunasd commented
Rebased and merged from other branch.

2021-11-17 19:05 UTC, closed without merging